### PR TITLE
test: adds fixture for https://github.com/elastic/apm/pull/344

### PR DESCRIPTION
**Pull request by astorm**
Adds a new test fixture to ensure  we cover the use case described in [apm#344](https://github.com/elastic/apm/pull/)

### CODE REVIEW

**Comment by felixbarny** [comment]
Are the underscores escaped to dashes, as mandated by the spec?

https://github.com/elastic/apm/pull/344/files

From the test case, it seems that's not the case. But maybe there's some post-processing in the agent itself?

**Comment by astorm** [comment]
@felixbarny Thank you -- I'd misread that part of the spec as describing the regular expression's form, and not as describing the regular expression's behavior. Since `container-info` is a package out there in the wild I'm guessing we that @Qard and @watson don't want that behavior in here, so it belongs in the agent. 

Re-opening https://github.com/elastic/apm-agent-nodejs/issues/1821 to have the underscore/dash discussion there. 

I'd still think there's value in landing this PR to ensure strings in this form remain parsed.

**Comment by Qard** [comment]
I'm happy to give you contributor access, if you want. I'm not using it anymore and don't have the time to maintain it myself at this point.

**Comment by astorm** [comment]
@Qard I'll take that contributor access just in case we need it.  Maintaining another open source project -- what could go wrong ;)

**Comment by Qard** [comment]
I've added you as a contributor here and on a few other projects used in the elastic agent. I can add you as a publisher for the npm modules too, if you give me your npm name.

**Comment by astorm** [comment]
Thank you @Qard, I appreciate it. I know that _too many open source projects_ feel.  

Also, my apologies, but when you have a free moment would you mind re-adding me as contributor to `object-identity-map`, `socket-location`, `http-request-to-url`, and `container-info`?  I attempted to accept the invitations today and they had all expired. I didn't realize GitHub enforced a time limite there.  

Also, my NPM user is `~alanstorm`.

Thanks again and best wishes.

**Comment by Qard** [comment]
Done. If Elastic wants to claim any of those modules and move them into the org, I'm cool with that too. I mostly only created them in my personal account because the process to create new modules within the org was a bit of a pain at the time, which made it easier to just make small modules like these under my own account.

**Pull request merged**
